# Generated by Django 6.0.5 on 2026-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=100)),
                ('userphone', models.CharField(max_length=100)),
                ('usercity', models.CharField(max_length=100)),
                ('userdestination', models.CharField(max_length=100)),
            ],
        ),
    ]
