# Generated by Django 6.0.5 on 2026-05-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='userdestination',
        ),
    ]
