# Generated by Django 6.0.5 on 2026-06-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_register_userdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_destination', models.CharField(max_length=100)),
            ],
        ),
    ]
