# Generated by Django 6.0.5 on 2026-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_booking_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_app',
            name='user_password',
        ),
        migrations.AddField(
            model_name='booking_app',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking_app',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking_app',
            name='user_phone',
            field=models.CharField(max_length=15),
        ),
    ]
