# Generated by Django 6.0.5 on 2026-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_booking_app_user_password_booking_app_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_c', models.CharField(max_length=100)),
                ('useremail_c', models.CharField(max_length=100)),
                ('userphone_c', models.CharField(max_length=100)),
                ('message_c', models.CharField(max_length=100)),
            ],
        ),
    ]
