# Generated by Django 6.0.5 on 2026-05-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('packagename', models.CharField(max_length=100)),
                ('package', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('days', models.DateField(max_length=100)),
            ],
        ),
    ]
