# Generated by Django 6.0.5 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details',
            name='days',
            field=models.CharField(max_length=100),
        ),
    ]
