# Generated by Django 6.0.5 on 2026-06-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_booking_status_delete_booking_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking_status',
            new_name='booking_app',
        ),
    ]
