# Generated by Django 6.0.5 on 2026-06-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_rename_booking_status_booking_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking_app',
        ),
    ]
