# Generated by Django 6.0.5 on 2026-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_hotel_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_hb', models.CharField(default='')),
                ('useremail_hb', models.CharField(default='')),
                ('userphone_hb', models.CharField(default='')),
                ('hotel_name', models.CharField(default='')),
                ('check_in', models.DateField(default='')),
                ('check_out', models.DateField(default='')),
                ('guest', models.CharField(default='')),
                ('vehicle_hb', models.CharField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='hotel_details',
        ),
    ]
